import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";

const DEFAULT_SKILLS_INDEX_URL = "https://code.deepline.com/.well-known/skills/index.json";
const indexUrl = new URL(process.env.DEEPLINE_SKILLS_INDEX_URL ?? DEFAULT_SKILLS_INDEX_URL);
const targetRoot = resolve(process.cwd(), "agent/skills");
const lockPath = resolve(process.cwd(), "agent/lib/deepline-skills-lock.ts");
const GENERATED_MARKER = ".deepline-well-known-skill";
const checkMode = process.argv.includes("--check");

type WellKnownSkillIndex = {
  version?: unknown;
  generated_at?: unknown;
  skills?: Array<{
    name?: unknown;
    files?: unknown;
  }>;
};

type SkillFileSnapshot = {
  path: string;
  sha256: string;
};

type SkillSnapshot = {
  name: string;
  files: SkillFileSnapshot[];
};

type SkillsLock = {
  sourceIndexUrl: string;
  indexVersion: string | null;
  indexGeneratedAt: string | null;
  generatedAt: string;
  skills: SkillSnapshot[];
};

const index = await readJson<WellKnownSkillIndex>(indexUrl);
if (!Array.isArray(index.skills)) {
  throw new Error(`Invalid Deepline well-known skills index: ${indexUrl.toString()}`);
}

mkdirSync(targetRoot, { recursive: true });

const snapshots: SkillSnapshot[] = [];
const downloadedFiles: Array<{
  skillName: string;
  path: string;
  body: string;
  sha256: string;
}> = [];

for (const skill of index.skills) {
  if (typeof skill.name !== "string" || !skill.name) {
    throw new Error(`Invalid skill entry in ${indexUrl.toString()}`);
  }
  if (!Array.isArray(skill.files)) {
    throw new Error(`Missing file list for Deepline skill ${skill.name}`);
  }

  const files: SkillFileSnapshot[] = [];
  for (const file of skill.files) {
    if (typeof file !== "string" || !file || file.includes("..")) {
      throw new Error(`Invalid file path for Deepline skill ${skill.name}`);
    }
    const sourceUrl = new URL(`${encodeURIComponent(skill.name)}/${file.split("/").map(encodeURIComponent).join("/")}`, indexUrl);
    const rawBody = file === "SKILL.md" ? normalizeSkillEntrypoint(await readText(sourceUrl)) : await readText(sourceUrl);
    const body = sanitizePublishedSkillFile(rawBody);
    const sha256 = hashText(body);
    files.push({ path: file, sha256 });
    downloadedFiles.push({ skillName: skill.name, path: file, body, sha256 });
  }

  if (!files.some((file) => file.path === "SKILL.md")) {
    throw new Error(`Missing SKILL.md for Deepline skill ${skill.name}`);
  }
  snapshots.push({ name: skill.name, files });
}

const nextLock: SkillsLock = {
  sourceIndexUrl: indexUrl.toString(),
  indexVersion: typeof index.version === "string" ? index.version : null,
  indexGeneratedAt: typeof index.generated_at === "string" ? index.generated_at : null,
  generatedAt: new Date().toISOString(),
  skills: snapshots,
};

if (checkMode) {
  assertSnapshotFresh(nextLock);
  console.log(`Deepline skill snapshot is up to date with ${indexUrl.toString()}`);
  process.exit(0);
}

removePreviouslyGeneratedSkills();

for (const file of downloadedFiles) {
  const targetPath = join(targetRoot, file.skillName);
  const targetFile = join(targetPath, file.path);
  mkdirSync(dirname(targetFile), { recursive: true });
  writeFileSync(targetFile, file.body);

  writeFileSync(
    join(targetPath, GENERATED_MARKER),
    [
      "Generated by scripts/sync-deepline-skills.ts.",
      `Source: ${indexUrl.toString()}`,
      "",
    ].join("\n"),
  );
}

writeSkillsLock(nextLock);

console.log(`Synced ${snapshots.length} Deepline well-known skills from ${indexUrl.toString()}`);

async function readJson<T>(url: URL): Promise<T> {
  return JSON.parse(await readText(url)) as T;
}

async function readText(url: URL): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url.toString()}: HTTP ${response.status}`);
  }
  return await response.text();
}

function removePreviouslyGeneratedSkills(): void {
  for (const entry of readdirSync(targetRoot)) {
    const candidate = join(targetRoot, entry);
    if (!statSync(candidate).isDirectory()) continue;
    if (!existsSync(join(candidate, GENERATED_MARKER))) continue;
    rmSync(candidate, { recursive: true, force: true });
  }
}

function normalizeSkillEntrypoint(raw: string): string {
  return raw.replace(/^disable-model-invocation:\s*(true|false)\s*\n/gm, "");
}

function sanitizePublishedSkillFile(raw: string): string {
  return raw
    .replace(/ada@gmail\.com/g, "ada@example.com")
    .replace(/mcastillo12692@gmail\.com/g, "mcastillo12692@example.com");
}

function hashText(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function writeSkillsLock(lock: SkillsLock): void {
  mkdirSync(dirname(lockPath), { recursive: true });
  writeFileSync(
    lockPath,
    [
      "// AUTO-GENERATED FILE. DO NOT EDIT.",
      "// Source: scripts/sync-deepline-skills.ts",
      `export default ${JSON.stringify(lock, null, 2)} as const;`,
      "",
    ].join("\n"),
  );
}

function assertSnapshotFresh(expectedLock: SkillsLock): void {
  const problems: string[] = [];
  if (!existsSync(lockPath)) {
    problems.push(`missing lockfile ${lockPath}`);
  } else {
    const currentLock = readSkillsLock();
    if (currentLock.sourceIndexUrl !== expectedLock.sourceIndexUrl) {
      problems.push(
        `lock source is ${currentLock.sourceIndexUrl}, expected ${expectedLock.sourceIndexUrl}`,
      );
    }
    if (currentLock.indexVersion !== expectedLock.indexVersion) {
      problems.push(
        `lock version is ${currentLock.indexVersion ?? "null"}, expected ${expectedLock.indexVersion ?? "null"}`,
      );
    }
    const currentSkills = JSON.stringify(lockComparable(currentLock.skills));
    const expectedSkills = JSON.stringify(lockComparable(expectedLock.skills));
    if (currentSkills !== expectedSkills) {
      problems.push("lock hashes do not match the published skill index");
    }
  }

  for (const skill of expectedLock.skills) {
    for (const file of skill.files) {
      const targetFile = join(targetRoot, skill.name, file.path);
      if (!existsSync(targetFile)) {
        problems.push(`missing ${skill.name}/${file.path}`);
        continue;
      }
      const actualHash = hashText(readFileSync(targetFile, "utf8"));
      if (actualHash !== file.sha256) {
        problems.push(`changed ${skill.name}/${file.path}`);
      }
    }
  }

  if (problems.length > 0) {
    throw new Error(`Skill snapshot is stale:\n- ${problems.join("\n- ")}`);
  }
}

function readSkillsLock(): SkillsLock {
  const raw = readFileSync(lockPath, "utf8");
  const match = raw.match(/^export default ([\s\S]*) as const;\s*$/m);
  if (!match) {
    throw new Error(`Invalid skills lockfile: ${lockPath}`);
  }
  return JSON.parse(match[1]) as SkillsLock;
}

function lockComparable(skills: SkillSnapshot[]): SkillSnapshot[] {
  return skills
    .map((skill) => ({
      name: skill.name,
      files: [...skill.files].sort((a, b) => a.path.localeCompare(b.path)),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
